# Generated by Django 3.2.7 on 2021-10-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.CharField(max_length=200, null=True)),
                ('Message', models.CharField(max_length=200, null=True)),
                ('Mobile_Number', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Code', models.CharField(max_length=200, null=True)),
                ('AC_No', models.IntegerField(default=0, null=True)),
                ('Part_No', models.IntegerField(default=0, null=True)),
                ('SI_No_In_Part', models.IntegerField(default=0, null=True)),
                ('Epic_No', models.CharField(max_length=200, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Age', models.IntegerField(default=0, null=True)),
                ('Gender', models.CharField(max_length=200, null=True)),
                ('RLn_Name', models.CharField(max_length=200, null=True)),
                ('RLN_Type', models.CharField(max_length=200, null=True)),
                ('Mobile_Number', models.BigIntegerField(default=0, null=True)),
            ],
        ),
    ]
