# Generated by Django 3.2.7 on 2021-10-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='Image_Url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
